import { StartupType } from "../types";

export const startups: StartupType[] = [
  {
    img: "/startups/AAA Logotext White.webp",
    title: "Digital agency for Web3 design and development:",
    description:
      "Get a website or DeFi webApp which suits your needs and goals, using top tier UI/UX and smart contracts integration.",
    link: "https://ascentadastra.com",
  },
  {
    img: "/startups/spectra_logo.png",
    title: "The derivatives layer for DeFi yield:",
    description:
      "Speculate on the evolution of the yield generated by different DeFi protocols. Hedge your risk on your passive revenue. Raised $3.6M across seed rounds led by Delphi Ventures and Greenfield Capital.",
    link: "https://www.spectra.finance/",
  },
  {
    img: "/startups/metacube-logo.png",
    title: "Free2Play Massive Multiplayer Game on Starknet:",
    description:
      "Join thousands of players in massively multiplayer events, compete to earn assets and use your wallet to see and manage your collection",
    link: "https://metacube.games/",
  },
  {
    img: "/startups/abstract-horizon.png",
    title: "Learn everything about the Abstract ecosystem:",
    description:
      "Abstract Horizon is the leading media about the Abstract Chain, a layer 2 blockchain focused on consumer applications.",
    link: "https://abstracthorizon.xyz/",
  },
  {
    img: "/startups/HONEY.webp",
    title: "Turn NFTs into financial assets:",
    description:
      "Honey Labs pioneers liquidity solutions for NFTs, and allows you to access DeFi through your NFTs.",
    link: "https://y.at/%F0%9F%8D%AF%F0%9F%8D%AF%F0%9F%90%9D",
  },
  {
    img: "/startups/abyss.png",
    title: "The perpetuals trading venue for Sui:",
    description:
      "Abyss is the trading venue built for everyone on Sui, where deep liquidity meets true on-chain freedom. A perp DEX powered by DeepBook V3 with margin trading up to 10x leverage and a Telegram bot for natural-language order execution.",
    link: "https://www.abyssprotocol.xyz/",
    imgClass: "max-h-20",
  },
  {
    img: "/startups/zyfai.png",
    title: "AI-powered DeFi portfolio management:",
    description:
      "Zyfai leverages artificial intelligence to optimize DeFi yield strategies and portfolio management. Raised $3M in seed funding from Marc Zeller (Aave), Francesco Andreoli (MetaMask), Everstake, Tenzor, and Brilliance Ventures.",
    link: "https://www.zyf.ai/",
  }
]; 